NAME=why_quantize_drive
VIEWPDF=evince
BIBTEXSRCS=why_quantize_drive.bib
USE_PDFLATEX=1
CLEAN_FILES+=why_quantize_drive.synctex.gz why_quantize_driveNotes.bib why_quantize_drive.fdb_latexmk why_quantize_drive.tar.gz *.bak *.tmp why_quantize_drive.fls
EXTRA_DIST+=*.pdf iop* 

include /usr/share/latex-mk/latex.gmk
